blueprint:
  name: UniFi Door Manager - Lockdown Sync
  description: >
    Keeps your Dashboard Lockdown Toggle in sync with the physical UniFi Master Switch and your specific door's rule.
    If you trigger a lockdown from the UniFi App (or the Master Switch), this automation forces your Dashboard Toggle ON
    so the Python script knows to pause.
  domain: automation
  input:
    dashboard_toggle:
      name: Dashboard Lockdown Toggle
      description: The input_boolean used in your Dashboard (e.g., input_boolean.lockdown_mode).
      selector:
        entity:
          domain: input_boolean
    master_switch:
      name: UniFi Master Switch
      description: The hardware switch that locks all doors (e.g., switch.all_doors_lockdown).
      selector:
        entity:
          domain: switch
    door_rule:
      name: Door Lock Rule
      description: The rule entity for your main door (e.g., select.front_door_rule).
      selector:
        entity:
          domain: select

mode: restart

trigger:
  - platform: state
    entity_id: !input master_switch
  - platform: state
    entity_id: !input door_rule

action:
  - if:
      - condition: or
        conditions:
          # Source A: Master Switch is ON
          - condition: state
            entity_id: !input master_switch
            state: "on"
          # Source B: Door Rule is 'keep_lock'
          - condition: state
            entity_id: !input door_rule
            state: "keep_lock"
          # Source C: Door Rule is 'keep_locked' (Variation)
          - condition: state
            entity_id: !input door_rule
            state: "keep_locked"
    then:
      - service: input_boolean.turn_on
        target:
          entity_id: !input dashboard_toggle
    else:
      - service: input_boolean.turn_off
        target:
          entity_id: !input dashboard_toggle
